version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /mnt/fatboi/jellyfin/config:/config
      - /mnt/fatboi/jellyfin/cache:/cache
      - /mnt/fatboi/media:/media
    restart: "unless-stopped"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
